### ISSUE TITLE
Feature Request: Define article (FAQ item) order

### ISSUE THREAD

**Issue by boldc** [sergiois/mod_articles_faq#1]
Hello, thanks for making this module available to the joomla community.  I was able to easily override the default_bootstrap3.php to work with my bootstrap 4 template.  However, I noticed that the output (articles as FAQ items) only appears to display in the order of article ID.  It would be fantastic if this module would allow the user to define the article order (ID, alphabetical, ordering ascending, etc) and therefore the order of the FAQ items.

Thanks again!

**Comment by sergiois** [comment]
Thanks @boldc for your suggestion. It is already implemented in version 1.2.x of the module
