### ISSUE TITLE
Emptying the search is not very clear

### ISSUE THREAD

**Issue by edthenet** [sergiois/mod_articles_faq#11]
When i use a search word, the list will shorten. This works.
But the searchfield is now empty, but in memory the entered information is still used

When ik click on the search field and hit the enter key the empty searchterm seems to be used and i get a full list again.

It would help if you added two things:
- Keep the use searchterm visible in the field
- Add a icon or button to clear the searchfield (and automatically hit enter after clearing)

**Comment by sergiois** [comment]
Thanks @edthenet for this issue and recomendarions.
In version 1.3.2 you have it fixed: https://github.com/sergiois/mod_articles_faq/releases/tag/v1.3.2
