### ISSUE TITLE
1.4.1 does not work with J3

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#12]
With Joomla 3 the 1.4 version will give the following error:
`Joomla\CMS\Form\Form::validateField() rule `CssIdentifier` missing.`
latest version for Joomla 3 is 1.3.2 

I do not know or that is on purpose or not. But this way other user also know it. :)

**Comment by sergiois** [comment]
Hello.
Yes, the last valid version for Joomla 3 is 1.3.2
It is specified on the web: https://sergiois.github.io/articles-faq.html#item-1-2

**Comment by Tazzios** [comment]
sorry, missed it.
