### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#13]
I added to line 48 of the default_bootstrap5.php file the following
`style="display: grid;grid-template-columns: repeat(auto-fit, minmax(20rem, 1fr));"`
Which result in this
![firefox_QQAnpKHmPc](https://github.com/sergiois/mod_articles_faq/assets/23451105/57d19545-f647-401a-acbf-32f650be89ec)

Problem is when clicked it will unfold the complete row:
![afbeelding](https://github.com/sergiois/mod_articles_faq/assets/23451105/d1be69c8-4ff5-4958-a5de-c80acd6aa96d)
I`m not that good that I know how to fix this. Instead of adding this as a style it probably would be better to use the existing class.

Possible config options: 
'auto-fit' could also be a number of columns, 1 for current behavior
20rem could also adjust.

**Comment by sergiois** [comment]
Hello Tazzios.
This module does not have support for custom styles.
Thanks for the contribution but the styles depend on each person.
All the best,
