### ISSUE TITLE
No count, default 5 articles

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#14]
When no count is given, default 5 is used. I would expect unlimited.

line 55 ArticlesFaqHelper.php
```
		if (  (int)$params->get('count')>0 ){			
			$model->setState('list.limit', (int) $params->get('count'));
		}
```

**Comment by sergiois** [comment]
Hello Tazzios.
You're right. It will be corrected in the next version.
Regards,
