### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#3]
I created an search option for the default_bootstrap3.php
It is still a bit raw without translation but a nice addon so i think. 

At line 40
```
<?php
if($params->get('show_search') == true) { ?>
    <form action="" method=""  >

        <input type="text" name="search" placeholder="doorzoek FAQ" />
        <input type="hidden" name="submit" value="Zoeken" />
    </form>
<?php } ?>

```

under the foreach (line 52 if you added above code.)
```
<?php
        // create text to search trough
	$Text = $item->title . ' ' . $item->introtext . ' ' .$item->fulltext;
	// get the search from the url if exist
	$search= $_GET["search"];

	If  (strpos($Text,$search) ==true || empty($search) ) {
		 
?>	
```
Replace second last line from
`<?php endforeach;  ?>`
To
`<?php } endforeach;  ?>`

to enable and disable it add  the next in at line 92 in the xml
```

<field
	name="show_search"
	type="radio"
	label="MOD_ARTICLES_FAQ_FIELD_SEARCH_SELECTION_LABEL"
	description="MOD_ARTICLES_FAQ_FIELD_SEARCH_SELECTION_DESC"
	class="btn-group btn-group-yesno"
	default="0"
	>
	<option value="1">JYES</option>
	<option value="0">JNO</option>
	</field>
```

**Comment by Tazzios** [comment]
#6 i created a branch for the search with the necessary translations.

**Comment by sergiois** [comment]
Thanks Tazzios!
Give me a few days to review all your comments and PR.

**Comment by sergiois** [comment]
Hello again!
The PRs sent are already depleted. Thanks for your contribution.
