### ISSUE TITLE
Number of Articles default wrong

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#4]
Count description says:
> Number of Articles to display (the default is All)

But in the code it is 3
`$model->setState('list.limit', (int) $params->get('count', 3));`

**Comment by sergiois** [comment]
Hello!
In version 1.3.0 this issue will be resolved along with other improvements to the code.
Thanks for your contribution.

**Comment by sergiois** [comment]
Version 1.3.0 is now available with your PR and some code improvements.
Thanks again!
