### ISSUE TITLE
Joomla Extension Directory error old version

### ISSUE THREAD

**Issue by Tazzios** [sergiois/mod_articles_faq#9]
The Joomla Extension Directory looks for version 1.3.0 instead of 1.3.1 using the webinstaller now gives an error

**Comment by Tazzios** [comment]
@sergiois  I see that you created a J4 version thank you!

if you update JED a lot more users will find the module.
https://extensions.joomla.org/extension/news-display/articles-display/articles-faq/

**Comment by sergiois** [comment]
Hello.
Yes, I have pending updating the information in the JED.
I'll update it as soon as I have time.
Thank you!
